### ISSUE TITLE
PSD variation options break pycbc inference

### ISSUE THREAD

**Issue by cdcapano** [ligo-cbc/pycbc#2085]
PR #2079  has broken `pycbc_inference`, perhaps `pycbc_inspiral` too. Trying to run `pycbc_inference`, I get:
```
Traceback (most recent call last):
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/bin/pycbc_inference", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==97rc816', 'pycbc_inference')
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/lib/python2.7/site-packages/PyCBC-97rc816-py2.7.egg/EGG-INFO/scripts/pycbc_inference", line 206, in <module>
    strain_dict, stilde_dict, psd_dict = option_utils.data_from_cli(opts)
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/lib/python2.7/site-packages/PyCBC-97rc816-py2.7.egg/pycbc/inference/option_utils.py", line 462, in data_from_cli
    precision="double")
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/lib/python2.7/site-packages/PyCBC-97rc816-py2.7.egg/pycbc/strain.py", line 443, in from_cli_multi_ifos
    strain[ifo] = from_cli_single_ifo(opt, ifo, **kwargs)
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/lib/python2.7/site-packages/PyCBC-97rc816-py2.7.egg/pycbc/strain.py", line 435, in from_cli_single_ifo
    return from_cli(single_det_opt, **kwargs)
  File "/work/cdcapano/virtualenv/pptests-pycbc_inference/lib/python2.7/site-packages/PyCBC-97rc816-py2.7.egg/pycbc/strain.py", line 425, in from_cli
    if opt.psdvar_short_segment is not None:
AttributeError: 'Namespace' object has no attribute 'psdvar_short_segment'
```
The issue appears to be that the psd variation options were added to `insert_strain_option_group`, but not to `insert_strain_option_group_multi_ifo`, which is what `pycbc_inference` (and I think `pycbc_inspiral`) uses.

**Comment by lauranuttall** [comment]
Should be fixed now with https://github.com/ligo-cbc/pycbc/pull/2086

**Comment by soumide1102** [comment]
Looks like it's still broken. My virtual environment did not pick the reverting commit from #2079 . I still get the error that @cdcapano reported.

**Comment by soumide1102** [comment]
Oops! Sorry.. the reverting was done in PR 2086, which is not merged yet.
