### ISSUE TITLE
Need mini-followup of missed injections

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#415]
The workflow should automatically generate mini-followups of the nearby missed injections.

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/425

**Comment by ahnitz** [comment]
Uh, this #425 doesn't really fix the issue. It doesn't add minifollowps,
just a table of which ones are missed.

**Comment by duncan-brown** [comment]
Initial version merged.
