### ISSUE TITLE
pycbc_calculate_psd should fail gracefully if its input segment file is empty

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#533]
At the moment it fails with
```python
Traceback (most recent call last):
  File "", line 80, in 
  File "/home/lppekows/pycbc-dev/src/pycbc/tools/static/build/pycbc_calculate_psd/out00-PYZ.pyz/pycbc.events.veto", line 198, in select_segments_by_definer
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by titodalcanton** [comment]
@duncan-brown do you have a full command line to test this?

**Comment by titodalcanton** [comment]
Resolved, see #570.

**Comment by duncan-brown** [comment]
Looks like this is not resolved:
```python
Traceback (most recent call last):
  File "", line 80, in 
  File "/home/lppekows/pycbc-dev/src/pycbc/tools/static/build/pycbc_calculate_psd/out00-PYZ.pyz/pycbc.events.veto", line 198, in select_segments_by_definer
IndexError: arrays used as indices must be of integer (or boolean) type
```
I will re-open and investigate.

**Comment by duncan-brown** [comment]
Test case on sugar-dev3 in 
```shell
cd /home/lppekows/projects/cbc/pycbc_release_tests/pre1.2.6/output/local-site-scratch/work/main_ID0000001
/home/lppekows/projects/cbc/pycbc_release_tests/pre1.2.6/output/local-site-scratch/work/main_ID0000001/calculate_psd-PART0-L1_ID56   --segment-end-pad   16   --segment-length   256   --low-frequency-cutoff   30   --pad-data   8   --sample-rate   4096   --segment-start-pad   112   --psd-segment-stride   8   --autogating-width   0.25   --psd-segment-length   16   --autogating-pad   16   --autogating-threshold   100   --autogating-cluster   0.5   --psd-estimation   median   --autogating-taper   0.25   --cores   4   --strain-high-pass   20   --channel-name   L1:GDS-CALIB_STRAIN   --analysis-segment-file   L1-INSPIRAL_DATA-0.xml   --segment-name   INSPIRAL_DATA   --frame-files   112400/L-L1_HOFT_C00-1124003840-4096.gwf   112400/L-L1_HOFT_C00-1124007936-4096.gwf   112401/L-L1_HOFT_C00-1124012032-4096.gwf   112401/L-L1_HOFT_C00-1124016128-4096.gwf   112402/L-L1_HOFT_C00-1124020224-4096.gwf   112402/L-L1_HOFT_C00-1124024320-4096.gwf   112402/L-L1_HOFT_C00-1124028416-4096.gwf   112403/L-L1_HOFT_C00-1124032512-4096.gwf   112403/L-L1_HOFT_C00-1124036608-4096.gwf   112404/L-L1_HOFT_C00-1124040704-4096.gwf   112404/L-L1_HOFT_C00-1124044800-4096.gwf   112404/L-L1_HOFT_C00-1124048896-4096.gwf   112405/L-L1_HOFT_C00-1124052992-4096.gwf   112405/L-L1_HOFT_C00-1124057088-4096.gwf   112406/L-L1_HOFT_C00-1124061184-4096.gwf   112406/L-L1_HOFT_C00-1124065280-4096.gwf   112406/L-L1_HOFT_C00-1124069376-4096.gwf   112407/L-L1_HOFT_C00-1124073472-4096.gwf   112407/L-L1_HOFT_C00-1124077568-4096.gwf   112408/L-L1_HOFT_C00-1124081664-4096.gwf   112408/L-L1_HOFT_C00-1124085760-4096.gwf   112408/L-L1_HOFT_C00-1124089856-4096.gwf   112409/L-L1_HOFT_C00-1124093952-4096.gwf   112409/L-L1_HOFT_C00-1124098048-4096.gwf   112410/L-L1_HOFT_C00-1124102144-4096.gwf   112410/L-L1_HOFT_C00-1124106240-4096.gwf   112411/L-L1_HOFT_C00-1124110336-4096.gwf   112411/L-L1_HOFT_C00-1124114432-4096.gwf   --output-file   L1-CALCULATE_PSD_PART0-1123945217-172800.hdf  
```

**Comment by duncan-brown** [comment]
Never mind, I am an idiot.
